services:
    oro_grid.orm.filter.type.date_range:
        class: Oro\Bundle\GridBundle\Filter\ORM\DateRangeFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_date_range }

    oro_grid.orm.filter.type.datetime_range:
        class: Oro\Bundle\GridBundle\Filter\ORM\DateTimeRangeFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_datetime_range }

    oro_grid.orm.filter.type.number:
        class:     Oro\Bundle\GridBundle\Filter\ORM\NumberFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_number }

    oro_grid.orm.filter.type.percent:
        class:     Oro\Bundle\GridBundle\Filter\ORM\PercentFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_percent }

    oro_grid.orm.filter.type.string:
        class:     Oro\Bundle\GridBundle\Filter\ORM\StringFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_string }

    oro_grid.orm.filter.type.choice:
        class:     Oro\Bundle\GridBundle\Filter\ORM\ChoiceFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_choice }

    oro_grid.orm.filter.type.select_row:
        class:     Oro\Bundle\GridBundle\Filter\ORM\SelectRowFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_select_row }

    oro_grid.orm.filter.type.boolean:
        class:     Oro\Bundle\GridBundle\Filter\ORM\BooleanFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_boolean }

    oro_grid.orm.filter.type.entity:
        class:     Oro\Bundle\GridBundle\Filter\ORM\EntityFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_entity }

    oro_grid.orm.filter.type.flexible_number:
        class:     Oro\Bundle\GridBundle\Filter\ORM\Flexible\FlexibleNumberFilter
        arguments: ["@pim_flexibleentity.registry", "@oro_grid.orm.filter.type.number"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_flexible_number }

    oro_grid.orm.filter.type.flexible_boolean:
        class:     Oro\Bundle\GridBundle\Filter\ORM\Flexible\FlexibleBooleanFilter
        arguments: ["@pim_flexibleentity.registry", "@oro_grid.orm.filter.type.boolean"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_flexible_boolean }

    oro_grid.orm.filter.type.flexible_string:
        class:     Oro\Bundle\GridBundle\Filter\ORM\Flexible\FlexibleStringFilter
        arguments: ["@pim_flexibleentity.registry", "@oro_grid.orm.filter.type.string"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_flexible_string }

    oro_grid.orm.filter.type.flexible_date_range:
        class:     Oro\Bundle\GridBundle\Filter\ORM\Flexible\FlexibleDateRangeFilter
        arguments: ["@pim_flexibleentity.registry", "@oro_grid.orm.filter.type.date_range"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_flexible_date_range }

    oro_grid.orm.filter.type.flexible_datetime_range:
        class:     Oro\Bundle\GridBundle\Filter\ORM\Flexible\FlexibleDateTimeRangeFilter
        arguments: ["@pim_flexibleentity.registry", "@oro_grid.orm.filter.type.datetime_range"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_flexible_datetime_range }

    oro_grid.orm.filter.type.flexible_options:
        class:     Oro\Bundle\GridBundle\Filter\ORM\Flexible\FlexibleOptionsFilter
        arguments: ["@pim_flexibleentity.registry", "@oro_grid.orm.filter.type.choice"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_flexible_options }

    oro_grid.orm.filter.type.flexible_entity:
        class:     Oro\Bundle\GridBundle\Filter\ORM\Flexible\FlexibleEntityFilter
        arguments: ["@pim_flexibleentity.registry", "@oro_grid.orm.filter.type.entity"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_flexible_entity }
